### ISSUE TITLE
Wo ist das Plugin ?

### ISSUE THREAD

**Issue by BogusCurry** [its-sparks-fly/Beitragsvorlage#1]
Hallo ;D
Hmm .. von der Beschreibung her, hört sich das alles gut an, aber wo ist das Plugin ? Ich sehe nur ein Readme in dem Repo ;D

Tschöö

Bogus

**Comment by its-sparks-fly** [comment]
Ahh, Bogus! Tut mir leid, dass du erst jetzt eine Antwort bekommst! ich war hier lange nicht aktiv, da ich GitHub nur um Test zur Auslagerung meiner Plugins benutzt habe. Ich habe das Plugin nun endlich angehangen. Tut mir leid!
